[project]
name = "pref-signaling"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "gym>=0.26.2",
    "gymnasium>=1.0.0",
    "ipykernel>=6.29.5",
    "pettingzoo>=1.24.3",
    "ray>=2.39.0",
]
